# Generated by Django 4.0.5 on 2022-07-03 13:29

import YogaWebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('description', models.TextField(max_length=191)),
                ('image', models.ImageField( upload_to='pics')),
                ('type', models.CharField(choices=[('D', 'Depression'), ('A', 'Anxiety'), ('S', 'Stress'), ('G', 'General')], max_length=1)),
            ],
        ),
    ]
