# Generated by Django 4.0.5 on 2022-08-12 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YogaWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(choices=[('1', 'Male'), ('2', 'Female')])),
                ('age', models.TextField(choices=[('0', 'below 19'), ('1', '19 to 23'), ('2', '24 to 40'), ('3', 'above 40')])),
                ('orientation', models.TextField(choices=[('1', 'Heterosexual'), ('2', 'Bisexual'), ('3', 'Homosexual'), ('4', 'Asexual'), ('5', 'Other')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.TextField(choices=[('1', 'Male'), ('2', 'Female')])),
                ('age', models.TextField(choices=[('0', 'below 19'), ('1', '19 to 23'), ('2', '24 to 40'), ('3', 'above 40')])),
                ('orientation', models.TextField(choices=[('1', 'Heterosexual'), ('2', 'Bisexual'), ('3', 'Homosexual'), ('4', 'Asexual'), ('5', 'Other')])),
            ],
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='description',
            field=models.TextField(),
        ),
    ]
