# Generated by Django 4.0.5 on 2022-08-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YogaWebsite', '0002_member_visitor_yogaclass_class_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depressionLvl', models.TextField(max_length=191)),
                ('anxietyLvl', models.TextField(max_length=191)),
                ('stressLvl', models.TextField(max_length=191)),
                ('submit_datetime', models.DateTimeField(default='2022-7-12 20:38:00', max_length=191)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YogaWebsite.visitor')),
            ],
            options={
                'verbose_name': 'Overall Test Result',
            },
        ),
        migrations.CreateModel(
            name='TestResultMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depressionLvl', models.TextField(max_length=191)),
                ('anxietyLvl', models.TextField(max_length=191)),
                ('stressLvl', models.TextField(max_length=191)),
                ('submit_datetime', models.DateTimeField(default='2022-7-12 20:38:00', max_length=191)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YogaWebsite.member')),
            ],
        ),
    ]
