# Generated by Django 4.0.5 on 2022-08-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YogaWebsite', '0004_testresultmember_user_yogaclass_class_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
