# Generated by Django 4.0.5 on 2022-08-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaWebsite', '0005_yogaclass_class_details_alter_testresultmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='class_details',
            field=models.TextField(default=''),
        ),
    ]
