# Generated by Django 4.0.5 on 2022-08-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YogaWebsite', '0006_yogaclass_class_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouchContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=191)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='yogaclass',
            options={'verbose_name_plural': 'Yoga Classes'},
        ),
    ]
